print("Hello, World!")
print(" amna")
print("first name:amna, last name: kiran")
print("1 2 3")
print("hello\nworld")
print("hello\tworld")
print(" apple, banana, cherry")
print("1-2-3")
print("hello world")
print("12")
print('"hello world"')
print("this is backslash\\")
print ("i am 21 years old")
print("This number is 4")
for number in range(6):
    print( "num", number)